### ISSUE TITLE
Allow user to adjust on front end?

### ISSUE THREAD

**Issue by jpequens** [brainstormforce/unlist-posts#31]
Hello -

I allow users to create their own posts on my site.  Was curious if there was an easy way to allow them to make their own posts unlisted on the front-end.  Thanks!

**Comment by Nikschavan** [comment]
Are you using any plugin to allow creating posts from frontend?

If that plugin provides some actions/filters to add new options to the form then it would be simple to insert a new field. 

Although I don't think this option should be shipped from this plugin as not all users will have a similar setup for creating the posts.

**Comment by jpequens** [comment]
I'm using ACF Front End, but was looking for a solution like this:  https://wordpress.stackexchange.com/questions/95545/post-visibility-option-to-theme-front-end-for-author-to-select

This allows the user to select 'Private' or 'Public'. Although, I might be over complicating things based on your comment.  I am fairly new to this stuff and was hoping for a nudge in the right direction.  

Thanks.

**Comment by Nikschavan** [comment]
Hey @jpequens - This plugin works simply by adding the post ID that is to be unlisted in an option - 

Here is the code how this is working in the WordPress admin - https://github.com/brainstormforce/unlist-posts/blob/28f0f96aa92431ae916e9a1b646227eca9d53d33/class-unlist-posts-admin.php#L136-L150

You can do something similar, add a custom checkbox and when that is checked and saved add the post Id to option `unlist_posts`
