### ISSUE TITLE
Conflict with WooCommerce Cart- Add On Plugin

### ISSUE THREAD

**Issue by supportvf** [brainstormforce/unlist-posts#49]
### Describe the bug:
Conflict with WooCommerce Cart- Add On Plugin. The WooCommerce extension doesn't seem to work when the Unlist plugin is Activated. The Extension doesn't show any product add-ons at all when this Unlist plugin is activated.

### To reproduce:
Install both WooCommerce Cart Add-On plugin and Unlist Posts plugin.

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
Version 5.6

**Comment by Nikschavan** [comment]
@supportvf - Is this this plugin that you are referring to? - https://woocommerce.com/products/cart-add-ons/

Since this is a premium plugin, It will be a little difficult for us to test and debug this. Can you add more screenshots etc to describe what is not working?

**Comment by Nikschavan** [comment]
Closing this issue as It is not possible for me to debug this plugin without any more information. Please feel free to reopen the issue if you have more information.
