### ISSUE TITLE
While there is a .pot file, there translation can't be done on translate.wordpress.org

### ISSUE THREAD

**Issue by NekoJonez** [brainstormforce/unlist-posts#63]
The .pot file isn't loaded in https://translate.wordpress.org/projects/wp-plugins/unlist-posts/

I think it would help translators when it's loaded into there so we don't have to renew our files every update ;)

**Comment by Nikschavan** [comment]
U have made a change in the plugin readme according to the [W.org docs](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain)

I will keep a watch on this if this gets fixed after the plugin translations are imported by translate.W.org

**Comment by Nikschavan** [comment]
This is fixed now @NekoJonez - https://translate.wordpress.org/projects/wp-plugins/unlist-posts/

You need to update to latest version 1.1.7 and the translations will load from https://translate.wordpress.org
